# Generated by Django 5.2.7 on 2025-10-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('head_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_group', to='accounts.studentprofile', verbose_name='Староста')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hours', models.IntegerField(default=0, verbose_name='Количество часов')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('year', models.IntegerField(verbose_name='Учебный год')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Назначение преподавателя',
                'verbose_name_plural': 'Назначения преподавателей',
                'unique_together': {('teacher', 'group', 'subject', 'semester', 'year')},
            },
        ),
    ]
